version: "3.5"
networks:
  nw:
    name: nw
    driver: bridge

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
           type: none
           device: /home/daniseed/data/wordpress
           o: bind
    db:
        name: mysql
        driver: local
        driver_opts:
            type: none
            device: /home/daniseed/data/mysql
            o: bind

services:
  nginx:
      build: ./nginx
      image: nginx
      container_name: nginx_container
      restart: always
      ports:
        - "443:443"
      depends_on:
        - wordpress
      networks:
        - nw
      volumes:
          - wordpress:/var/www/wordpress
  wordpress:
      build: ./wordpress
      image: wordpress
      container_name: wordpress_container
      restart: always
      env_file: .env
      user: root
      depends_on:
        - mysql
      networks:
        - nw
      volumes:
          - wordpress:/wordpress
  mysql:
      build:
        context: ./mysql
        args:
          - ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
          - USER=$MYSQL_USER
          - PASSWORD=$MYSQL_PASSWORD
      image: mysql
      container_name: db_container
      restart: always
      env_file: .env
      user: root
      networks:
        - nw
      volumes:
          - db:/var/lib/mysql
