
CREATE USER $MYSQL_USER@'%' IDENTIFIED WITH $MYSQL_PASSWORD;
GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON wordpress.* TO $MYSQL_USER@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY $MYSQL_ROOT_PASSWORD;
